=== hmcts/cpp-context-notification-notify/notificationnotify-command/notificationnotify-command-handler/src/raml/json/schema/notificationnotify.command.ingest-file.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/notificationnotify/notificationnotify.command.ingest-file.json",
  "type": "object",
  "properties": {
    "fileId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "sourceUri": {
      "type": "string"
    },
    "correlationId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "filename": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "fileId",
    "sourceUri",
    "correlationId",
    "filename"
  ]
}

=== hmcts/cpp-context-notification-notify/notificationnotify-command/notificationnotify-command-handler/src/raml/json/notificationnotify.command.ingest-file.json
{
  "fileId": "184416a9-ef20-4500-a9c1-f64b87b424a9",
  "sourceUri": "https://storage.blob.core.windows.net/mi-reportdata/published/reports/184416a9-ef20-4500-a9c1-f64b87b424a9?sv=2021-08-06&se=2026-05-15T12%3A00%3A00Z&sr=b&sp=r&sig=example",
  "correlationId": "384416a9-ef20-4500-a9c1-f64b87b424a0",
  "filename": "live_report_2026-05-15.csv"
}
